// <auto-generated />
using BhShopifyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace BhShopifyApp.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal
            .NpgsqlAnnotationProvider.SetPostgresVersion(modelBuilder, 14, 0);

        modelBuilder.Entity("BhShopifyApp.Models.ShopSession", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<string>("Shop").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<string>("AccessToken").IsRequired().HasColumnType("text");
            b.Property<string>("Scopes").IsRequired().HasColumnType("text");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("Shop").IsUnique();
            b.ToTable("Sessions");
        });

        modelBuilder.Entity("BhShopifyApp.Models.ShopSettings", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<string>("Shop").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<string>("ErpBaseUrl").IsRequired().HasColumnType("text");
            b.Property<string>("ErpApiKey").IsRequired().HasColumnType("text");
            b.Property<string>("ErpApiHeader").IsRequired().HasDefaultValue("X-Api-Key").HasColumnType("text");
            b.Property<bool>("SyncEnabled").HasDefaultValue(true).HasColumnType("boolean");
            b.Property<int>("SyncIntervalMinutes").HasDefaultValue(15).HasColumnType("integer");
            b.Property<DateTime?>("LastSyncAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("Shop").IsUnique();
            b.ToTable("ShopSettings");
        });
#pragma warning restore 612, 618
    }
}
